server:
  port: 8080
  context-path: #/liuzh/

  tomcat:
    protocol_header: x-forwarded-proto
  use-forward-headers: true
  address: 127.0.0.1


security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3

logging:
  level:
    tk.mybatis: trace
    java.sql: trace
    #org.springframework: DEBUG
  file: /var/log/meblog.log

# BANNER
banner:
  charset: UTF-8 # Banner file encoding.
  location: classpath:banner.txt # Banner file location.

spring:


  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 1000Mb

  datasource:
      name: test
      url: jdbc:mysql://localhost:3306/zblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: cloud
      password: d05660
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

  freemarker:
    cache: false
    request-context-attribute: request


mybatis:
  type-aliases-package: org.cloud.pestle.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql